# Generated by Django 5.0.3 on 2024-04-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Voter',
        ),
    ]
