# Generated by Django 5.0.3 on 2024-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_user_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('custom_password_field', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Voter',
            new_name='SignUpVoter',
        ),
    ]
