# Generated by Django 5.0.3 on 2024-04-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_newvoteregistrationdata_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newvoteregistrationdata',
            old_name='father_name',
            new_name='assembly_constituency',
        ),
        migrations.RemoveField(
            model_name='newvoteregistrationdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='newvoteregistrationdata',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='newvoteregistrationdata',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='newvoteregistrationdata',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='newvoteregistrationdata',
            name='application_reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='newvoteregistrationdata',
            name='epic_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='photo',
            field=models.ImageField(default='', max_length=255, upload_to='DP_photos/'),
        ),
    ]
