# Generated by Django 5.0.3 on 2024-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_father_name_newvoteregistrationdata_assembly_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvoteregistrationdata',
            name='district_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newvoteregistrationdata',
            name='state_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
