# Generated by Django 5.0.3 on 2024-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_newvoteregistrationdata_district_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='email_id',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='resident_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
