# Generated by Django 5.0.3 on 2024-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_newvoteregistrationdata_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='address_proof_document',
            field=models.FileField(upload_to='DataBase/address_proof_documents/'),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='disabilityDocuments',
            field=models.FileField(blank=True, null=True, upload_to='DataBase/disability_documents/'),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='dob_document',
            field=models.FileField(upload_to='DataBase/dob_documents/'),
        ),
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='photo',
            field=models.ImageField(default='', max_length=255, upload_to='DataBase/DP_photos/'),
        ),
    ]
