# Generated by Django 5.0.3 on 2024-04-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_newvoteregistrationdata_address_proof_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvoteregistrationdata',
            name='resident_since',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
