# Generated by Django 5.0.3 on 2024-03-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.ImageField(upload_to='party_symbols/')),
            ],
        ),
        migrations.CreateModel(
            name='polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('epic_number', models.CharField(max_length=50, unique=True)),
                ('polling_station_number', models.CharField(max_length=50)),
                ('iris_verification', models.BooleanField(default=False)),
                ('fingerprint_verification', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('voted_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polling.politicalparty')),
            ],
        ),
    ]
