# Generated by Django 5.0.3 on 2024-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='voted_party',
        ),
        migrations.RemoveField(
            model_name='polling',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='polling',
            name='otp_verified',
        ),
        migrations.AddField(
            model_name='polling',
            name='aadhaar_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='polling',
            name='captcha_text',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='polling',
            name='polling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='polling',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='polling',
            name='epic_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='polling',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='polling',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='polling',
            name='polling_station_number',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.DeleteModel(
            name='PoliticalParty',
        ),
    ]
