# Generated by Django 5.0.3 on 2024-04-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_remove_polling_voted_party_remove_polling_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='polling',
        ),
        migrations.AddField(
            model_name='polling',
            name='vote',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='polling',
            name='aadhaar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='polling',
            name='captcha_text',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='polling',
            name='epic_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polling',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='polling',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='polling',
            name='polling_station_number',
            field=models.CharField(max_length=5),
        ),
    ]
