# Generated by Django 5.0.3 on 2024-04-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_remove_polling_polling_polling_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='captcha_text',
        ),
    ]
