# Generated by Django 5.0.3 on 2024-04-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0006_rename_email_poll_email_id'),
        ('registration', '0009_alter_newvoteregistrationdata_resident_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('party_voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.party')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.newvoteregistrationdata')),
            ],
        ),
        migrations.DeleteModel(
            name='poll',
        ),
    ]
