# Generated by Django 5.0.3 on 2024-04-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0007_party_vote_delete_poll'),
        ('registration', '0009_alter_newvoteregistrationdata_resident_since'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'party_voted')},
        ),
    ]
