# Generated by Django 5.0.3 on 2024-04-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0008_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='captured_image',
            field=models.ImageField(default='', upload_to='DataBase/vote_images/'),
        ),
    ]
